### ISSUE TITLE
Unclear what to do wtih Pre_BuildFileList.py

### ISSUE THREAD

**Issue by guysoft** [jchristel/SampleCodeRevitBatchProcessor#1]
Hey, I am looking for a way to update the file list (if a file by the name exist in the folder, where it was already upgraded, then use that folder).

There seems to be something like that here:
https://github.com/jchristel/SampleCodeRevitBatchProcessor/blob/Revit-2019/Pre_BuildFileList.py
Description says 
```
sample description
# this sample shows how to build a task list file (used as a pre-process)
```

Where is this used and how does it alter the list? Does it run before?

**Comment by jchristel** [comment]
Hi,

Yes this script is used as a Pre-Process by batch processor. You can select it in the user interface when enabling Advanced Settings.

I attached an image for your reference. Let me know whether that answered your question.

J

![PreProcess](https://user-images.githubusercontent.com/1165990/102417888-bdc07480-4050-11eb-88ef-00b31336dcbc.png)

**Comment by jchristel** [comment]
In addition: to the above:
The script writes the file path of all revit project files in a given folder into a task list file.
When creating the settings file for this task to run, I put an empty task list file in the specified location first knowing that the pre process will essentially over write that file and populate it with file data.
Creating an empty file first allows me to select it in the UI when setting up the task.
J

**Comment by guysoft** [comment]
Ok that's useful. I thought of using that to exclude files already processed. For example when batch-upgrading files.

**Comment by guysoft** [comment]
Ok, I got time to go over this, so will note the default empty script that you get if you click ``New Script ...`` button next to the pre/post processing sectinon is this:

```python3
import clr
import System
clr.AddReference("System.Core")
clr.ImportExtensions(System.Linq)

import script_util
from script_util import Output

sessionId = script_util.GetSessionId()

# NOTE: this only make sense for batch Revit file processing mode.
revitFileListFilePath = script_util.GetRevitFileListFilePath()

# NOTE: these only make sense for data export mode.
sessionDataFolderPath = script_util.GetSessionDataFolderPath()
dataExportFolderPath = script_util.GetExportFolderPath()

# TODO: some real work!
Output()
Output("This pre-processing script is running!")

```
which comes from here: https://github.com/bvn-architecture/RevitBatchProcessor/blob/master/BatchRvtUtil/Scripts/template_pre_processing_script.py

Mentioning because ``script_util.GetRevitFileListFilePath()`` was useful.
It lets me pull the list and then modify it (for example, remove files that already were converted/processed).
