### ISSUE TITLE
[request] purge unused line styles

### ISSUE THREAD

**Issue by kirsch33** [jchristel/SampleCodeRevitBatchProcessor#14]
Hi all, I've found this repo to be very helpful as of late and appreciate all the hard work.

Would it be possible to implement a delete/purge unused line style function? I see currently the only available similar option is to remove them by name.

**Comment by jchristel** [comment]
Hi Austin,

I'm glad to see this is being useful for others too! 

@petersmithfromengland Has done some work in that area. We will keep you posted on the progress.

**Comment by petersmithfromengland** [comment]
Hi @kirsch33 

I have just committed to my own branch (ps_WIP-0.1.2) a function which will purge unused line patterns which should clean up them. I will move onto line styles soon but hope this may help you in the mean time

Cheers, Pete

**Comment by kirsch33** [comment]
@petersmithfromengland thanks for the update, looking forward to it!

**Comment by jchristel** [comment]
Purge line pattern is now available in official release version of duHast
