### ISSUE TITLE
[help] comparing titleblock families

### ISSUE THREAD

**Issue by kirsch33** [jchristel/SampleCodeRevitBatchProcessor#19]
hi all, I am looking for some advice regarding a project I want to implement. i work within an AEC firm that is multidisciplinary and we sometimes struggle with having consistent titleblocks between disciplines. it is silly since its something that is so easy to get correct, but regardless I want to leverage my powers to try and catch these things programmatically before drawing reviews.

in my mind, this can go 1 of 2 ways.

1. leverage duHast family data to gather all text, text positioning, image info, and linework geometry from a titleblock known to be correct (or at least that will be the basis for comparison). then recursively open all Revit files within project directory and extract titleblock family info for comparison against the basis. 
2. subdivide titleblock into regions and export as images. exclude region that has sheet number and revision block info, then compare region images between disciplines to determine % matching 

I would prefer option 1, but we have some disciplines which still use AutoCAD (sitework, electrical) which forces my hand into option 2.

This all being said, I would appreciate if you all had any advice for how duHast could be applied here to assist me! does there exist any functionality to export an image from a view via API? or maybe you all have a better idea entirely? 😆

**Comment by jchristel** [comment]
Hi, 

Uh that is a tricky one. I don't think duHast offers quite the capability you are after...In particular text, text positioning and by extension labels and label position is not covered.

There is some code in the Categories section which returns all appearance properties of lines etc in a family but again no positional information.

I would probably lean into option 2 but maybe a simple pdf comparison? Not sure how one would go about though and automate that...

**Comment by jchristel** [comment]
Closing Issue as per the above.
