### ISSUE TITLE
Do documintation on how to use debug_ = False

### ISSUE THREAD

**Issue by guysoft** [jchristel/SampleCodeRevitBatchProcessor#2]
Hey,
So I am writing code, and it seems like there is an undocumented way to debug scripts. At the moment I have to edit the script and run it via Revit Batch Processor, which could take a while to test.

However I see some scripts have this

```
debug_ = False
```
How do I use that?

Example: https://github.com/jchristel/SampleCodeRevitBatchProcessor/blob/Revit-2019/ModifyRevitLinksWorksetByList_executeThis.py#L34

**Comment by jchristel** [comment]
Hi,
I use Revit python shell to debug the scripts in Revit. In the case of running the script through the shell, the batch processor modules are not available which is when the above debug_ flag is set to True.

Hope that helps?

J

**Comment by guysoft** [comment]
That helps. I wanted to know how you are testing it. ATM I am mostly testing by running via RBP
