### ISSUE TITLE
Code example to generate a design from parameters

### ISSUE THREAD

**Issue by yomomano** [jchristel/SampleCodeRevitBatchProcessor#7]
Hi Jan, forgive to use this issue tracker to ask a question. 

I am looking for a way to generate a design by parsing a custom (parameters) file that holds information of location and name of element/family instance. The script should add the elements to an existing Revit file and save file when done.

I didn't find an example of creating elements in a Revit file in any of your examples. Is this because it is not supported by Revit/RBP? If possible, where could I look for more info? 

Thanks so much!

**Comment by jchristel** [comment]
Hi Yomomano,

You are quite right: all of the samples in the repository centre either on reporting properties or amending properties of elements, not o much creating elements.

That's got to do with the fact that my (work) focus is on maintaining a library of Revit families and check in on and improve model health, not so much a limitation of the Revit API.

I would have a look in the Dynamo Forum to maybe get some ideas on how to create elements in Revit through the API.

Jan

**Comment by jchristel** [comment]
This guy covers a lot of Revit API topics:

https://thebuildingcoder.typepad.com
